// landings
export const CREATE_LANDING = 'CREATE_LANDING';
export const EDIT_LANDING = 'EDIT_LANDING';
export const GET_LANDING_INFO = 'GET_LANDING_INFO';
export const GET_PROGRAMS_COUNT = 'GET_PROGRAMS_COUNT';
export const FETCH_LANDINGS = 'FETCH_LANDINGS';
export const FILTER_LANDINGS = 'FILTER_LANDINGS';

// Programs
export const GET_PROGRAM_INFO = 'GET_PROGRAM_INFO';
export const FETCH_PROGRAMS = 'FETCH_PROGRAMS';
export const FILTER_PROGRAMS = 'FILTER_PROGRAMS';
export const SAVE_PROGRAM = 'SAVE_PROGRAM';
export const SET_TEMPLATE = 'SET_TEMPLATE';
